publicHoistPattern:
  - '*eslint*' # @battis/eslint-config
  - '*prettier*' # @battis/prettier-config

allowBuilds:
  # development environment
  '@battis/eslint-config': true
  '@battis/prettier-config': true
  nx: true # lerna
  unrs-resolver: true # jest

  # @battis/webpack peer dependencies needed for webpack builds only
  '@parcel/watcher': false # sass
  gifsicle: false
  jpegtran-bin: false
  optipng-bin: false
  sharp: false

packages:
  - packages/*
