publicHoistPattern:
  - '*eslint*'
  - '*prettier*'

allowBuilds:
  '@parcel/watcher': true
  gifsicle: true
  jpegtran-bin: true
  nx: true
  optipng-bin: true
  sharp: true
  unrs-resolver: true

packages:
  - packages/*
