allowBuilds:
  '@parcel/watcher': true # sass
  gifsicle: true
  jpegtran-bin: true
  optipng-bin: true
  sharp: true
publicHoistPattern:
  - '*-loader'
  - dotenv-webpack
  - favicons
  - 'imagemin*'
  - 'postcss*'
  - sass
  - typescript
  - '*-webpack-plugin'
  - 'webpack*'
